package com.blog.pojo;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


import java.io.Serializable;

@Data
@TableName("tb_admin_user")
@NoArgsConstructor
@AllArgsConstructor
public class TbAdminUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.admin_user_id
     *
     * @mbggenerated
     */
    @TableId
    private Integer adminUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.login_user_name
     *
     * @mbggenerated
     */
    @TableField("login_user_name")
    private String loginUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.login_password
     *
     * @mbggenerated
     */
    @TableField("login_password")
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.nick_name
     *
     * @mbggenerated
     */
    @TableField("nick_name")
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.locked
     *
     * @mbggenerated
     */
    @TableField("locked")
    private Integer locked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.email
     *
     * @mbggenerated
     */
    @TableField("email")
    private String email;
}