package com.blog.pojo;

import io.lettuce.core.dynamic.annotation.Command;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "tb_blog_comment")
public class TbBlogComment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.comment_id
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "comment_id")
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.blog_id
     *
     * @mbggenerated
     */
    @Column(name = "blog_id")
    private Integer blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.commentator
     *
     * @mbggenerated
     */
    @Column(name = "commentator")
    private String commentator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.email
     *
     * @mbggenerated
     */
    @Column(name = "email")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.website_url
     *
     * @mbggenerated
     */
    @Column(name = "website_url")
    private String websiteUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.comment_body
     *
     * @mbggenerated
     */
    @Column(name = "comment_body")
    private String commentBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.comment_create_time
     *
     * @mbggenerated
     */
    @Column(name = "comment_create_time")
    private Date commentCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.commentator_ip
     *
     * @mbggenerated
     */
    @Column(name = "commentator_ip")
    private String commentatorIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.reply_body
     *
     * @mbggenerated
     */
    @Column(name = "reply_body")
    private String replyBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.reply_create_time
     *
     * @mbggenerated
     */
    @Column(name = "reply_create_time")
    private Date replyCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.comment_status
     *
     * @mbggenerated
     */
    @Column(name = "comment_status")
    private Integer commentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_comment.is_deleted
     *
     * @mbggenerated
     */
    @Column(name = "is_deleted")
    private Integer isDeleted;
}