package com.blog.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;


@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "tb_blog_category")
public class TbBlogCategoryEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.category_id
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "category_id")
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.category_name
     *
     * @mbggenerated
     */
    @Column(name = "category_name")
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.category_icon
     *
     * @mbggenerated
     */
    @Column(name = "category_icon")
    private String categoryIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.category_rank
     *
     * @mbggenerated
     */
    @Column(name = "category_rank")
    private Integer categoryRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.is_deleted
     *
     * @mbggenerated
     */
    @Column(name = "is_deleted")
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.create_time
     *
     * @mbggenerated
     */
    @Column(name = "create_time")
    private Date createTime;

}