package com.blog.pojo;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


import java.io.Serializable;
import java.util.Date;


@Data
@AllArgsConstructor
@NoArgsConstructor
@TableName("tb_blog_category")
public class TbBlogCategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.category_id
     *
     * @mbggenerated
     */
    @TableId
    @TableField("category_id")
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.category_name
     *
     * @mbggenerated
     */
    @TableField("category_name")
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.category_icon
     *
     * @mbggenerated
     */
    @TableField("category_icon")
    private String categoryIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.category_rank
     *
     * @mbggenerated
     */
    @TableField("category_rank")
    private Integer categoryRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.is_deleted
     *
     * @mbggenerated
     */
    @TableField("is_deleted")
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_blog_category.create_time
     *
     * @mbggenerated
     */
    @TableField("create_time")
    private Date createTime;

}